config/routes.rb
Rails.application.routes.draw do


  get 'live_chat/index'
  get 'bookings/create'
  get 'home' => 'home#index'
  get '/side' => 'home#side'
  root 'landing#index'

  resources :search, controller: 'search', only: [:create]
  get '/search' => 'search#create', as: 'search'
  post '/search/filter' => 'search#filter', as: 'search_filter'

  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:update, :create, :show, :new] do
      resources :educations
      resources :experiences
      resources :skills
      resources :languages
      resources :projects
      resources :jobhunter, controller: "jobhunters", only: [:index, :new, :create, :update, :edit]
    get "/about_me" => 'users#about_me'
    get "/edit_name" => 'users#edit_name'
    get "/edit_about_me" => 'users#edit_about_me'
    get "/edit_email" => 'users#edit_email'
    get "/edit_phone" => 'users#edit_phone'
    get "/edit_birthday" => 'users#edit_birthday'
    get "/edit_location" => 'users#edit_location'
    patch "/add_skill" => 'users#add_skill'
    delete "/remove_skill/:id" => 'users#remove_skill', as: 'remove_skill'

    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]

    resources :employer, controller: "employers", only: [:edit, :update, :create]
  end

  resources :conversation, controller: "conversations", only: [:index, :show]
  resources :personal_messages, only: [:new, :create]

  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  # For employer
  get "/employer/dasboard" => "employers#dashboard", as: "employer_dashboard"
  # get "/employer/analysis" => "analysis#index", as: "employer_analysis"
  get "/employer/jobs" => 'jobs#index', as: 'jobs_index'
  get "/employer/company/:id/timeline_page" => "employer_timelines#index", as: "timeline_page"
  get "/employer/company/:id/review_page" => "employers#review_page", as: "review_page"
  resources :employer, controller: 'employers', only: [:index, :new] do
    resource :review, controller: 'reviews', only: [:create, :new, :destroy]
  end
  resources :company, controller: 'companies', only: [:index, :new, :create, :show] do
    resource :follow, controller: "follows", only: [:create, :destroy]
    get '/about' => 'companies#about', as: 'about'
    get '/reviews' => 'companies#reviews', as: 'reviews'
    resources :jobs, controller: "jobs", only: [:show, :new, :create, :edit] do
      resources :booking, controller: 'bookings', only: [:new, :create, :show]
    end
  end
  resources :booking, controller: 'bookings', only: [:index]

  delete "/employer_jobs/:id" => "employer_jobs#delete", as: "delete_employer_job"
  delete "/employer_timelines/:id" => "employer_timelines#delete", as: "delete_employer_timeline"


  post '/user-pre-employer' => 'users#create_pre_employer', as: 'create_pre_employer'
  resources :employer_timelines, controller: "employer_timelines"







  get "/employer/review_analysis" => "analysis#review_analysis", as: "employer_review_analysis"
  get "/employer/job_analysis" => "analysis#job_analysis", as: "employer_job_analysis"
  get "/employer/applicant_analysis" => "analysis#applicant_analysis", as: "employer_applicant_analysis"
  get "/employer/follower_analysis" => "analysis#follower_analysis", as: "employer_follower_analysis"

  get "/ssss" => "conversations#something", as: "something"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login
  def index
    if current_user.employer
      redirect_to employer_dashboard_path
    end
    @jobs = Job.all.includes(:company),
    @companies = Company.all.includes(:employer)
    @employers = Employer.order(jobhunters_count: :desc)

    timeline = Array.new
    timeline += [@jobs, @companies]
    @timeline = timeline.flatten.sort_by {|obj| obj.updated_at}.reverse.first(6)
    if Employer.find_by(user_id: current_user.id)
  		@employer = Employer.find_by(user_id: current_user.id)
  		@company = Company.find_by(employer_id: @employer.id)
  	end
  end

  def side
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about_me.html.erb
<div class="card">
  <div class="card-body">
    <div class="avatar-container-home">
      <%=image_tag(current_user.avatar_url(:thumb_home), class: "rounded-circle d-block mx-auto", style: "width:200px;height:200px;")%>
    </div>
    <div class="user-about-me-home my-2">
      <h5><strong>About Me</strong></h5>
      <p><%=current_user.email%></p>
      <%= link_to "Update Profile", user_path(current_user.id), method: :get, class: 'btn btn-primary font-weight-bold' %>
      <p class="small-font my-2 text-muted">Last Updated: <%=current_user.updated_at.strftime("%b %e")%></p>
    </div>
  </div>
</div>

app/views/home/_jobs_dashboard.html.erb
<div class="col-8">
  <div class="card">
    <div class="card-body">
      <h5 class="m-0">
        <strong>Recent Updates</strong>
      </h5>
      <p class="text-muted m-0">
        What's been happening lately!
      </p>
    </diV>
  </div>
  <div class="my-3 searchresult-container-home">
    <ul class="list-unstyled">
      <% @timeline.uniq.map do |obj| %>
        <% if obj.is_a?(Job)%>
        <li>
          <div class="card my-2">
            <div class="row">
              <div class="col-2">
                <div class="card-body">
                  <%=image_tag(obj.company.logo_url, class:'d-block mx-auto', style: 'width:55px;height:55px;')%>
                </div>
              </div>
              <div class="col-7">
                <div class="card-body pl-0">
                  <h5 class="text-primary card-title mb-1"><strong><%=obj.title%></strong></h5>
                  <p class="my-1 small-font"><%=obj.company.name%></p>
                  <p class="my-1 text-muted small-font"><%=obj.location%></p>
                </div>
              </div>
              <div class="col-3">
                <div class="card-body">
                  <%=link_to "Apply Now", company_job_path(obj.company.id, obj.id), class: 'btn btn-primary'%>
                  <br/>
                  <br/>
                  <p class=" m-0 mt-2 text-center text-muted"><%=obj.updated_at.strftime('%b %e')%></p>
                </div>
              </div>
            </div>
          </div>
        </li>
        <% elsif obj.is_a?(Company)%>
        <li>
          <div class="card my-2">
            <div class="row">
              <div class="col-2">
                <div class="card-body">
                  <%=image_tag(obj.logo_url, class:'d-block mx-auto', style: 'width:55px;height:55px;')%>
                  <p class="my-2 border p-1 font-weight-bold reviews text-center small-font"><%=obj.employer.reviews.count%> <i class="far fa-smile"></i></p>
                </div>
              </div>
              <div class="col-7">
                <div class="card-body pl-0">
                  <h5 class="text-primary card-title mb-1"><strong><%=obj.name%></strong></h5>
                  <p class="my-1 text-muted small-font"><%=obj.location%></p>
                </div>
              </div>
              <div class="col-3">
                <div class="card-body px-2">
                  <%=link_to "View Company", company_path(obj.id), target: '_blank', class: 'btn btn-primary'%>
                  <br/>
                  <br/>
                  <p class=" m-0 mt-2 text-center text-muted"><%=obj.updated_at.strftime('%b %e')%></p>
                </div>
              </div>
            </div>
          </div>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/_most_reviewed_employers.html.erb
<div class="card my-2">
  <div class="card-body">
    <h5><strong>Most Reviewed Employers</strong></h5>
    <div class="d-flex flex-wrap flex-row my-2 justify-content-center">
      <% if @employers.present? %>
        <%@employers.limit(8).each do |employer| %>
          <%=link_to company_path(employer.company.id) do %>
            <%=image_tag(employer.company.logo_url, class: 'rounded-circle m-2', style: 'width:50px;height:50px;')%>
          <% end %>
        <%end%>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_my_dashboard.html.erb
<div class="col-4">
  <%=render partial: 'home/about_me' %>
  <%=render partial: 'home/most_reviewed_employers' %>
</div>

app/views/home/index.html.erb
<% content_for :navbar_user do %>
    <%= render partial: "navbar/user_navbar" %>
<% end %>
<div class="container mt-4">
  <div class="row">
    <%= render partial: 'home/my_dashboard' %>
    <%= render partial: 'home/jobs_dashboard' %>
  </div>
</div>

app/views/home/side.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white card p-0">
  <div class="container-fluid p-0">
    <img src="/assets/jobcrop_logo.png" width="30" height="30" alt="">
  </div>
</nav>
<div class="side-container-bg">
  <div class="container side-container d-flex flex-fill align-items-center">
    <div class="w-100 choose-container p-5">
      <h4 class="font-weight-bold text-white text-center mb-4">Choose A Side</h4>
      <div class="row">
        <div class="col-6">
          <%=link_to "Jobhunter", new_user_jobhunter_path(current_user.id), class: 'btn btn-primary w-100 btn-lg'%>
        </div>
        <div class="col-6">
          <%=link_to "Employer", new_employer_path, class: 'btn btn-danger w-100 btn-lg'%>
        </div>
      </div>
    </div>
  </div>
</div>