config/routes.rb
Rails.application.routes.draw do


  get 'live_chat/index'
  get 'bookings/create'
  get 'home' => 'home#index'
  get '/side' => 'home#side'
  root 'landing#index'

  resources :search, controller: 'search', only: [:create]
  get '/search' => 'search#create', as: 'search'
  post '/search/filter' => 'search#filter', as: 'search_filter'

  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:update, :create, :show, :new] do
      resources :educations
      resources :experiences
      resources :skills
      resources :languages
      resources :projects
      resources :jobhunter, controller: "jobhunters", only: [:index, :new, :create, :update, :edit]
    get "/about_me" => 'users#about_me'
    get "/edit_name" => 'users#edit_name'
    get "/edit_about_me" => 'users#edit_about_me'
    get "/edit_email" => 'users#edit_email'
    get "/edit_phone" => 'users#edit_phone'
    get "/edit_birthday" => 'users#edit_birthday'
    get "/edit_location" => 'users#edit_location'
    patch "/add_skill" => 'users#add_skill'
    delete "/remove_skill/:id" => 'users#remove_skill', as: 'remove_skill'

    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]

    resources :employer, controller: "employers", only: [:edit, :update, :create]
  end

  resources :conversation, controller: "conversations", only: [:index, :show]
  resources :personal_messages, only: [:new, :create]

  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  # For employer
  get "/employer/dasboard" => "employers#dashboard", as: "employer_dashboard"
  # get "/employer/analysis" => "analysis#index", as: "employer_analysis"
  get "/employer/jobs" => 'jobs#index', as: 'jobs_index'
  get "/employer/company/:id/timeline_page" => "employer_timelines#index", as: "timeline_page"
  get "/employer/company/:id/review_page" => "employers#review_page", as: "review_page"
  resources :employer, controller: 'employers', only: [:index, :new] do
    resource :review, controller: 'reviews', only: [:create, :new, :destroy]
  end
  resources :company, controller: 'companies', only: [:index, :new, :create, :show] do
    resource :follow, controller: "follows", only: [:create, :destroy]
    get '/about' => 'companies#about', as: 'about'
    get '/reviews' => 'companies#reviews', as: 'reviews'
    resources :jobs, controller: "jobs", only: [:show, :new, :create, :edit] do
      resources :booking, controller: 'bookings', only: [:new, :create, :show]
    end
  end
  resources :booking, controller: 'bookings', only: [:index]

  delete "/employer_jobs/:id" => "employer_jobs#delete", as: "delete_employer_job"
  delete "/employer_timelines/:id" => "employer_timelines#delete", as: "delete_employer_timeline"


  post '/user-pre-employer' => 'users#create_pre_employer', as: 'create_pre_employer'
  resources :employer_timelines, controller: "employer_timelines"







  get "/employer/review_analysis" => "analysis#review_analysis", as: "employer_review_analysis"
  get "/employer/job_analysis" => "analysis#job_analysis", as: "employer_job_analysis"
  get "/employer/applicant_analysis" => "analysis#applicant_analysis", as: "employer_applicant_analysis"
  get "/employer/follower_analysis" => "analysis#follower_analysis", as: "employer_follower_analysis"

  get "/ssss" => "conversations#something", as: "something"
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def new
		@user = User.find(params[:user_id])
		@projects = @user.projects
		respond_to do |format|
		  format.js
		end
	end

	def create
		@user = User.find(params[:user_id])
		@project = @user.projects.build(project_params)
		@projects = @user.projects

		if @project.save
			flash[:success] = "Project added."
			respond_to do |format|
			  format.js
			end
		else
			flash[:error] = "Something's wrong. #{@project.errors.full_messages.to_sentence}"
			redirect_back(fallback_location: @user)
		end
	end

	def edit
		@user = User.find(params[:user_id])
		@project = Project.find(params[:id])
		respond_to do |format|
		  format.js
		end
	end

	def update
		@user = User.find(params[:user_id])
		@project = Project.find(params[:id])
		@projects = @user.projects

		if @project.update(project_params)
			flash[:success] = "Project updated"
			respond_to do |format|
			  format.js
			end
		else
			flash[:error] = "Somehing's wrong. #{@project.erros.full_messages.to_sentence}"
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		@projects = @user.projects
		@project = Project.find(params[:id])
		@project.destroy
		respond_to do |format|
		  format.js
		end
	end

	private
	def project_params
		params.require(:project).permit(
			:name,
			:description
		)
	end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_create_project.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(scope: :project, url: user_projects_path(@user.id), method: 'POST' ) do |f| %>
      <div class="form-group">
        <%=f.label "Project Name"%>
        <%=f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%=f.label "Description"%>
        <%=f.text_area :description, class: 'form-control', rows: '4'%>
      </div>
      <%=f.submit "Add new project", class: 'btn btn-primary btn-sm'%>
      <%= link_to "Cancel", user_path(@user), class: 'mx-2' %>
    <% end %>
  </div>
</div>

app/views/projects/_edit_project.html.erb
<%= form_with(scope: :project, url: user_project_path(@user.id, @project.id), method: 'PATCH' ) do |f| %>
  <div class="form-group">
    <%=f.label "Project Name"%>
    <%=f.text_field :name, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%=f.label "Description"%>
    <%=f.text_area :description, class: 'form-control', rows: '4'%>
  </div>
  <%=f.submit "Apply", class: 'btn btn-primary btn-sm'%>
  <%= link_to "Cancel", user_path(@user), class: 'mx-2' %>
<% end %>

app/views/projects/_projects-timeline.html.erb
<%@projects.limit(3).each do |project| %>
  <div class="card my-2">
    <div class="card-body project-card-<%=project.id%>">
      <p class="card-title font-weight-bold">
        <%=project.name%>
        <% if current_user.own_profile?(@user) %>
          <%=link_to edit_user_project_path(@user.id, project.id), id: "editProject-#{project.id}", remote:true do%>
            <i class="edit fas fa-pen"></i>
          <% end %>
          <%=link_to user_project_path(@user.id, project.id), id: "removeProject-#{project.id}", method: 'DELETE', remote:true, data: {confirm: "Are you sure about removing this language?"} do%>
            <i class="edit fas fa-trash-alt"></i>
          <% end %>
        <%end%>
      </p>
      <p class="card-text text-muted">
        <%= sanitize project.description %>
      </p>
    </div>
  </div>
<%end%>

app/views/projects/create.js.erb
$('.projects-list').html("<%= j render 'projects/projects-timeline', projects: @projects%>")

app/views/projects/destroy.js.erb
$('.projects-list').html("<%= j render 'projects/projects-timeline', projects: @projects%>")

app/views/projects/edit.js.erb
$('.project-card-<%=@project.id%>').html("<%= j render 'projects/edit_project'%>")

app/views/projects/new.js.erb
$('.projects-list').html("<%= j render 'projects/create_project'%>");

app/views/projects/show.html.erb
<h2>Project</h2>

<%= link_to 'Profile', users_profile_path %>

<table>
		<th>Project name</th>
		<th>Project details</th>
		<th>Image</th>
		
	
		<tr>
			<td><%= @project.project_name %></td>
			<td><%= @project.project_details %></td>
			<td><%= @project.image %></td>
		</tr>	
	
</table>

app/views/projects/update.js.erb
$('.projects-list').html("<%= j render 'projects/projects-timeline', projects: @projects%>");