config/routes.rb
Rails.application.routes.draw do


  get 'live_chat/index'
  get 'bookings/create'
  get 'home' => 'home#index'
  get '/side' => 'home#side'
  root 'landing#index'

  resources :search, controller: 'search', only: [:create]
  get '/search' => 'search#create', as: 'search'
  post '/search/filter' => 'search#filter', as: 'search_filter'

  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:update, :create, :show, :new] do
      resources :educations
      resources :experiences
      resources :skills
      resources :languages
      resources :projects
      resources :jobhunter, controller: "jobhunters", only: [:index, :new, :create, :update, :edit]
    get "/about_me" => 'users#about_me'
    get "/edit_name" => 'users#edit_name'
    get "/edit_about_me" => 'users#edit_about_me'
    get "/edit_email" => 'users#edit_email'
    get "/edit_phone" => 'users#edit_phone'
    get "/edit_birthday" => 'users#edit_birthday'
    get "/edit_location" => 'users#edit_location'
    patch "/add_skill" => 'users#add_skill'
    delete "/remove_skill/:id" => 'users#remove_skill', as: 'remove_skill'

    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]

    resources :employer, controller: "employers", only: [:edit, :update, :create]
  end

  resources :conversation, controller: "conversations", only: [:index, :show]
  resources :personal_messages, only: [:new, :create]

  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  # For employer
  get "/employer/dasboard" => "employers#dashboard", as: "employer_dashboard"
  # get "/employer/analysis" => "analysis#index", as: "employer_analysis"
  get "/employer/jobs" => 'jobs#index', as: 'jobs_index'
  get "/employer/company/:id/timeline_page" => "employer_timelines#index", as: "timeline_page"
  get "/employer/company/:id/review_page" => "employers#review_page", as: "review_page"
  resources :employer, controller: 'employers', only: [:index, :new] do
    resource :review, controller: 'reviews', only: [:create, :new, :destroy]
  end
  resources :company, controller: 'companies', only: [:index, :new, :create, :show] do
    resource :follow, controller: "follows", only: [:create, :destroy]
    get '/about' => 'companies#about', as: 'about'
    get '/reviews' => 'companies#reviews', as: 'reviews'
    resources :jobs, controller: "jobs", only: [:show, :new, :create, :edit] do
      resources :booking, controller: 'bookings', only: [:new, :create, :show]
    end
  end
  resources :booking, controller: 'bookings', only: [:index]

  delete "/employer_jobs/:id" => "employer_jobs#delete", as: "delete_employer_job"
  delete "/employer_timelines/:id" => "employer_timelines#delete", as: "delete_employer_timeline"


  post '/user-pre-employer' => 'users#create_pre_employer', as: 'create_pre_employer'
  resources :employer_timelines, controller: "employer_timelines"







  get "/employer/review_analysis" => "analysis#review_analysis", as: "employer_review_analysis"
  get "/employer/job_analysis" => "analysis#job_analysis", as: "employer_job_analysis"
  get "/employer/applicant_analysis" => "analysis#applicant_analysis", as: "employer_applicant_analysis"
  get "/employer/follower_analysis" => "analysis#follower_analysis", as: "employer_follower_analysis"

  get "/ssss" => "conversations#something", as: "something"
end

app/models/company.rb
class Company < ApplicationRecord
  mount_uploader :logo, LogoUploader

  belongs_to :employer
  has_many :jobs, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :jobhunters, through: :follows
  has_many :company_timelines
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def index
		if current_user.employer
			@employer = current_user.employer
			@company = @employer.company
		else
			redirect_to employer_index_path
		end
	end
	def new
		@employer = current_user.employer
	end

	def create
		@employer = current_user.employer
		@company = @employer.build_company(company_params)
		if @company.save
			redirect_to root_path
		else
			flash[:danger] = @company.errors.full_messages.to_sentence
			redirect_back(fallback_location: root_path)
		end
	end

	def show
		@company = Company.find(params[:id])
		@employer = @company.employer
	end

	def about
		@company = Company.find(params[:company_id])
		respond_to do |format|
		  format.js
		end
	end

	def reviews
		@company = Company.find(params[:company_id])
		@reviews = Review.where(employer_id: @company.employer.id).includes(:jobhunter)
		respond_to do |format|
		  format.js
		end
	end

	private

	def company_params
		params.require(:company).permit(:name, :website, :telephone, :background, :location, :size, :logo)
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
	
end

app/views/companies/_about.html.erb
<div class="card mb-2 bg-light">
  <div class="card-body">
    <h5 class="card-title font-weight-bold m-0">Jobs by <%=@company.name%> <span class="text-muted">(<%=@company.jobs.count%>)</span></h5>
    <hr/>
    <div class="jobs-carousel">
      <%@company.jobs.each do |job| %>
        <%=link_to company_job_path(job.company.id, job.id), class: 'nav-link p-0', target: '_blank' do %>
        <div class="card job-carousel-card">
          <div class="card-body">
            <p class="text-center medium-font"><%=job.title%></p>
            <hr/>
            <p class="medium-font"><%=truncate(job.location, length: 40)%></p>
            <p class="medium-font text-muted"><%=number_to_currency(job.salary, unit: 'RM', precision: 0)%></p>
          </div>
          <div class="card-footer">
            <p class="m-0 small-font"><%=job.created_at.strftime('%b %e')%></p>
          </div>
        </div>
        <% end %>
      <%end%>
    </div>
  </div>
</div>
<div class="card my-2">
  <div class="card-body">
    <h5 class="card-title font-weight-bold">Company Background</h5>
    <p class="card-text"><%= sanitize @company.background %></p>
  </div>
</div>

app/views/companies/_new.html.erb
<%=form_with(scope: :company, url: company_index_path(@employer.id), method: 'POST', local: true) do |f| %>
  <div class="form-group">
    <h5 class="text-muted">Upload your company logo</h5>
    <%= f.file_field :logo, class: 'form-control-file' %>
  </div>
  <div class="form-group">
    <h5 class="text-muted">What's your company name?</h5>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <h5 class="text-muted">Where is it located at?</h5>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
  <div class="form-group">
    <h5 class="text-muted">Give a brief intro about your company.</h5>
    <%= f.text_area :background, class: 'form-control', rows: '8' %>
  </div>
  <div class="form-group">
    <h5 class="text-muted">How many employees does your company have?</h5>
    <%= f.select(:size,
                  options_for_select([
                    ['0-10','0-10'],
                    ['10-50','10-50'],
                    ['50-100', '50-100'],
                    ['100-500', '100-500'],
                    ['500+','500+']
                  ]), {},
                  {class: 'custom-select w-50 d-block mx-auto'}) %>
  </div>
  <hr/>
  <div class="form-inline">
      <%= f.text_field :website, class: 'form-control mx-2', placeholder: 'Website(Optional)' %>
      <%= f.text_field :telephone, class: 'form-control mx-2', placeholder: 'Office Tel' %>
  </div>
  <%=f.submit "Create Employer Account", class: "m-3 btn btn-primary d-block mx-auto btn-lg" %>


<% end %>

app/views/companies/_reviews.html.erb
<div class="card mb-2">
  <div class="card-body">
    <h5 class="card-title font-weight-bold m-0">Reviews</h5>
  </div>
</div>
<%=link_to "Write a review", new_employer_review_path(@company.id), class: 'btn btn-primary w-100 write-review', remote:true%>
<div class="create-form"></div>
<ul class="list-unstyled reviews-tab">
  <%=render partial: 'reviews/reviews-list'%>
</ul>

app/views/companies/about.js.erb
$('.company-profile-tab').html("<%= j render 'companies/about', companies: @companies%>");
$('.jobs-carousel').slick({
  infinite: true,
  slidesToShow: 3,
  slidesToScroll: 3
});

app/views/companies/index.html.erb
<%= render partial: "navbar/employer_navbar" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-2 bg-white border-right">
      <%=render partial: 'navbar/employer_sidebar'%>
    </div>
    <div class="col-10 py-3">
      <div class="card">
        <div class="card-body">
          <%=image_tag(@company.logo_url, class:'rounded-circle d-block mx-auto mb-3', style: "width:150px;height:150px;")%>
          <h5 class="font-weight-bold text-center"><%= @company.name %></h5>
          <p class="text-center"><%= @company.location %></p>
          <hr/>
          <ul class="nav">
            <li class="nav-item mx-auto">Followers: <%=@company.follows.count%> </li>
            <li class="nav-item mx-auto">Jobs: <%=@company.jobs.count%> </li>
          </ul>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-9">
          <div class="card mb-2">
            <div class="card-body">
              <h5 class="card-title font-weight-bold">Company Photos</h5>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title font-weight-bold">Company Background</h5>
              <p class="card-text"><%= sanitize @company.background %></p>
            </div>
          </div>
        </div>
        <div class="col-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title font-weight-bold">Company Information<h5>
                <ul class="list-unstyled">
                  <li>
                    <p class="medium-font mb-1">Company Size:</p>
                    <p class="medium-font"><%= @company.size%> employees</p>
                  </li>
                  <li>
                    <p class="medium-font mb-1">Company Website:</p>
                    <p class="medium-font"><%= @company.website%></p>
                  </li>
                  <li>
                    <p class="medium-font mb-1">Office Tel:</p>
                    <p class="medium-font"><%= @company.telephone%></p>
                  </li>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/reviews.js.erb
$('.company-profile-tab').html("<%= j render 'companies/reviews'%>");
$('.jobs-carousel').slick({
  infinite: true,
  slidesToShow: 3,
  slidesToScroll: 3
});

changeNumber()
function changeNumber(){
    var elements= document.getElementsByClassName("rating");
    for (var i=0; i<elements.length; i++) {
        var element = elements[i];
        var length = parseInt(element.innerHTML);
        var x=Array(length+1).join('<i class="fas fa-star"></i>');
        element.innerHTML=x;
    }
}

app/views/companies/show.html.erb
<% content_for :navbar_user do %>
  <% if signed_in? %>
    <%= render partial: "navbar/user_navbar" %>
  <% else %>
    <%= render partial: "navbar/visitor_navbar" %>
  <% end %>
<% end %>
<div class="container mt-3">
  <div class="card">
    <div class="card-body">
      <%=image_tag(@company.logo_url, class:'rounded-circle d-block mx-auto mb-3', style: "width:150px;height:150px;")%>
      <h5 class="font-weight-bold text-center"><%= @company.name %></h5>
      <p class="text-center"><%= @company.location %></p>
      <hr/>
      <ul class="nav">
        <li class="nav-item mx-auto">Followers: <%=@company.follows.count%> </li>
        <li class="nav-item mx-auto">Jobs: <%=@company.jobs.count%> </li>
        <li class="nav-item mx-auto">Reviews: <%=@company.employer.reviews.count%> </li>
      </ul>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-9">
      <div class="card mb-2">
        <div class="card-body p-2">
          <ul class="nav nav-fill">
            <li class="nav-item">
              <%=link_to "About", company_about_path(@company.id), class: 'nav-link', remote:true%>
            </li>
            <li class="nav-item">
              <%=link_to "Reviews", company_reviews_path(@company.id), class: 'nav-link', remote:true%>
            </li>
          </ul>
        </div>
      </div>
    <div class="company-profile-tab">
      <%=render partial: 'companies/about'%>
    </div>
    </div>
    <div class="col-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title font-weight-bold">Company Information<h5>
            <ul class="list-unstyled">
              <li>
                <p class="medium-font mb-1">Company Size:</p>
                <p class="medium-font"><%= @company.size%> employees</p>
              </li>
              <li>
                <p class="medium-font mb-1">Company Website:</p>
                <p class="medium-font"><%= @company.website%></p>
              </li>
              <li>
                <p class="medium-font mb-1">Office Tel:</p>
                <p class="medium-font"><%= @company.telephone%></p>
              </li>
            </ul>
        </div>
      </div>
      <div class="follow-container mt-2">
        <% if @company.follows.find_by(jobhunter_id: current_user.jobhunter.id).blank? %>
          <%=link_to "Follow", company_follow_path(@company.id), method: 'post', class: 'btn btn-primary follow-btn w-100'%>
        <% else %>
          <%=link_to "Unfollow", company_follow_path(@company.id), method: 'delete', class: 'btn btn-danger follow-btn w-100'%>
        <% end %>
        <%=link_to "Message", new_personal_message_path(receiver_id: @company.employer), class: 'btn btn-warning my-2 d-block mx-auto', remote:true %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="newMessage" tabindex="-1" role="dialog" aria-labelledby="newMessage" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>