config/routes.rb
Rails.application.routes.draw do


  get 'live_chat/index'
  get 'bookings/create'
  get 'home' => 'home#index'
  get '/side' => 'home#side'
  root 'landing#index'

  resources :search, controller: 'search', only: [:create]
  get '/search' => 'search#create', as: 'search'
  post '/search/filter' => 'search#filter', as: 'search_filter'

  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:update, :create, :show, :new] do
      resources :educations
      resources :experiences
      resources :skills
      resources :languages
      resources :projects
      resources :jobhunter, controller: "jobhunters", only: [:index, :new, :create, :update, :edit]
    get "/about_me" => 'users#about_me'
    get "/edit_name" => 'users#edit_name'
    get "/edit_about_me" => 'users#edit_about_me'
    get "/edit_email" => 'users#edit_email'
    get "/edit_phone" => 'users#edit_phone'
    get "/edit_birthday" => 'users#edit_birthday'
    get "/edit_location" => 'users#edit_location'
    patch "/add_skill" => 'users#add_skill'
    delete "/remove_skill/:id" => 'users#remove_skill', as: 'remove_skill'

    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]

    resources :employer, controller: "employers", only: [:edit, :update, :create]
  end

  resources :conversation, controller: "conversations", only: [:index, :show]
  resources :personal_messages, only: [:new, :create]

  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  # For employer
  get "/employer/dasboard" => "employers#dashboard", as: "employer_dashboard"
  # get "/employer/analysis" => "analysis#index", as: "employer_analysis"
  get "/employer/jobs" => 'jobs#index', as: 'jobs_index'
  get "/employer/company/:id/timeline_page" => "employer_timelines#index", as: "timeline_page"
  get "/employer/company/:id/review_page" => "employers#review_page", as: "review_page"
  resources :employer, controller: 'employers', only: [:index, :new] do
    resource :review, controller: 'reviews', only: [:create, :new, :destroy]
  end
  resources :company, controller: 'companies', only: [:index, :new, :create, :show] do
    resource :follow, controller: "follows", only: [:create, :destroy]
    get '/about' => 'companies#about', as: 'about'
    get '/reviews' => 'companies#reviews', as: 'reviews'
    resources :jobs, controller: "jobs", only: [:show, :new, :create, :edit] do
      resources :booking, controller: 'bookings', only: [:new, :create, :show]
    end
  end
  resources :booking, controller: 'bookings', only: [:index]

  delete "/employer_jobs/:id" => "employer_jobs#delete", as: "delete_employer_job"
  delete "/employer_timelines/:id" => "employer_timelines#delete", as: "delete_employer_timeline"


  post '/user-pre-employer' => 'users#create_pre_employer', as: 'create_pre_employer'
  resources :employer_timelines, controller: "employer_timelines"







  get "/employer/review_analysis" => "analysis#review_analysis", as: "employer_review_analysis"
  get "/employer/job_analysis" => "analysis#job_analysis", as: "employer_job_analysis"
  get "/employer/applicant_analysis" => "analysis#applicant_analysis", as: "employer_applicant_analysis"
  get "/employer/follower_analysis" => "analysis#follower_analysis", as: "employer_follower_analysis"

  get "/ssss" => "conversations#something", as: "something"
end

app/models/education.rb
class Education < ApplicationRecord
	belongs_to :user
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

	def index
		@user = User.find(params[:user_id])
		@education = Education.where(user_id: @user.id)
		respond_to do |format|
			format.js
		end
	end

	def create
		@user = current_user
		@education = @user.educations.build(education_params)

		if @education.save
			flash[:success] = "Education Added!"
			redirect_to @user
		else
			flash[:error] = "Something Wrong. #{@education.errors.full_messages.to_sentence}"
			redirect_to @user
		end
	end

	def edit
		@user = User.find(params[:user_id])
		@education = Education.find(params[:id])
		respond_to do |format|
		  format.js
		end
	end

	def update
		@user = User.find(params[:user_id])
		@education = Education.find(params[:id])
		if @education.update(education_params)
			flash[:success] = "Education Updated"
			respond_to do |format|
			  format.js
			end
		else
			flash[:error] = "Something wrong. #{@education.errors.full_messages.to_sentence}"
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		@education = Education.find(params[:id])
		@education.destroy
		redirect_back(fallback_location: @user)
	end

	private
	def education_params
		params.require(:education).permit(
			:institute,
			:qualification,
			:location,
			:major,
			:description,
			:graduation_year,
			:currently_studying
		)
	end

end

app/views/educations/_edit_education.html.erb
<%= form_with(scope: :education, url: user_education_path(@user.id, @education.id), method: 'PATCH' ) do |f| %>
  <%= f.text_field :institute, placeholder: "Institute", class: 'form-control bg-light border-0 my-2' %>
  <%= f.text_field :qualification, placeholder: "Qualification", class: 'form-control bg-light border-0 my-2' %>
  <%= f.text_field :location, placeholder: "Location", class: 'form-control bg-light border-0 my-2' %>
  <%= f.text_field :major, placeholder: "Major", class: 'form-control bg-light border-0 my-2' %>
  <div class="form-inline">
    <p class="m-0 text-muted mr-2">Graduation Year: </p>
    <%= f.date_field :graduation_year, class: 'form-control bg-light border-0 my-2' %>
    <p class="m-0 mx-2 text-muted">Currently studying?</p>
    <%= f.check_box :currently_studying %>
  </div>
  <%= f.text_area :description, placeholder: "Description", class: 'form-control bg-light border-0 my-2' %>
  <%= f.submit "Apply", class: 'btn btn-outline-secondary my-2' %>
  <%= link_to "Cancel", user_path(@user), class: 'mx-2' %>
<% end %>

app/views/educations/_education_card.html.erb
<div class="d-flex flex-row">
  <h5 class="card-title font-weight-bold mr-auto"><%=education.institute%></h5>
  <%=link_to edit_user_education_path(@user.id, education.id), id: "editEducation-#{education.id}", remote:true do%>
    <i class="edit fas fa-pen"></i>
  <% end %>
  <%=link_to user_education_path(@user.id, education.id), id: "removeEducation-#{education.id}", method: 'DELETE', remote:true, data: {confirm: "Are you sure about removing this education?"} do%>
    <i class="edit fas fa-trash-alt"></i>
  <% end %>
</div>
<p class="card-text m-0"><%=education.major%></p>
<p class="card-text"><%=education.qualification%></p>
<div class="d-flex flex-row">
  <p class="text-muted mr-auto"><%=education.location%></p>
  <p class="text-muted ml-auto">Graduation: <%=education.graduation_year%></p>
</div>
<p class="card-text"><%=education.description%></p>

<script>
$('#editEducation-<%=education.id%>').hide();
$('#removeEducation-<%=education.id%>').hide();
$('#education-card-<%=education.id%>').on('mouseover', function(){
  $('#editEducation-<%=education.id%>').show();
  $('#removeEducation-<%=education.id%>').show();
}).on('mouseleave', function(){
  $('#editEducation-<%=education.id%>').hide();
  $('#removeEducation-<%=education.id%>').hide();
})
</script>

app/views/educations/edit.js.erb
$('#education-card-<%=@education.id%>').html("<%= j render 'educations/edit_education' %>");

app/views/educations/index.js.erb
$('.profile-tab').html("<%= j render 'users/profile/education' %>")

app/views/educations/update.js.erb
$('#education-card-<%=@education.id%>').html("<%= j render 'educations/education_card', education: @education %>");